Shell exercises

diff --git a/loops_conditions_and_parsing/1-for_best_school b/loops_conditions_and_parsing/1-for_best_school
--- a/loops_conditions_and_parsing/1-for_best_school
+++ b/loops_conditions_and_parsing/1-for_best_school
@@ -6,3 +6,4 @@ do
 	echo "Best school"
 	((i++))
 done
+>&2 echo "error"
